config/routes.rb
Rails.application.routes.draw do

  get 'test', to: 'petitions#test'
  
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  devise_for :users

  scope(:path => '/api/v1') do
    resources :profiles
    resources :science_degrees, only: [:index, :show, :update, :create]
    resources :education_degrees, only: [:index, :show, :update, :create]
    resources :workplaces, only: [:index, :show, :update, :create]
    resources :awards, except: [:new, :edit]
    resources :users, except: [:new, :edit]
    resources :award_types, only: [:index, :show, :update, :create]
    resources :award_type_categories, only: [:index]
    resources :petition_initiators, only: [:index, :show, :update, :create]
    resources :document_qualities, only: [:index, :show, :update, :create]
    resources :award_categories, only: [:index]

    get 'petitions/new_count', to: 'admin_petitions#new_count'
    resources :petitions, controller: 'admin_petitions', as: 'admin_petitions' do
      member do
        get 'similar'
        post 'import'
      end
    end

    resources :petitioners
    get 'account/current', to: 'application#current_account'

    resources :reports, only: [:create, :index]
  end

  # petitions
  resources :petitions
  devise_for :petitioners, controllers: {
    sessions: 'petitioners/sessions',
    registrations: 'petitioners/registrations',
    confirmations: 'petitioners/confirmations'
  }
end

app/models/petitioner.rb
class Petitioner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable
  validates :name, :post, :phone, :workplace, :address, presence: true
  validates :password, presence: true, on: :create
  validates_confirmation_of :password, on: :create
  validates_uniqueness_of :email

  has_many :petitions
end

app/controllers/petitioners/confirmations_controller.rb
class Petitioners::ConfirmationsController < Devise::ConfirmationsController
  def show
    super do |resource|
      sign_in(resource) if resource.errors.empty?
    end
  end
end

app/controllers/petitioners/registrations_controller.rb
class Petitioners::RegistrationsController < Devise::RegistrationsController
 
  before_filter :configure_permitted_parameters

  def new
    @petitioner = Petitioner.new
    render 'petitioners/sign_up'
  end

  def create
    super do
      if resource.errors.any?
        flash[:danger] = resource.errors.full_messages
        @petitioner = resource
        render 'petitioners/sign_up' 
        return
      end
    end
  end

  def after_sign_up_path_for(resource)
    petitions_path
  end

  def after_sign_in_path_for(resource)
    petitions_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :phone, :post, :workplace, :address, :email, :password, 
               :password_confirmation)
    end
  end
end

app/controllers/petitioners/sessions_controller.rb
class Petitioners::SessionsController < Devise::SessionsController
  def new
    if petitioner_signed_in?
      redirect_to petitions_path
      return
    end
    @petitioner = Petitioner.new
    render 'petitioners/sign_in'
  end
end

app/controllers/petitioners_controller.rb
class PetitionersController < ApplicationController
  before_filter :authenticate_user!, except: :test

  def index
    render json: Petitioner.select(:id, :name, :email).all
  end

end

app/views/petitioners/confirm_email.slim
.row
  .col-xs-12
    .well style="padding:0"
      .alert.alert-warning.text-center
        h2 Ви не підтвердили вашу емейл адресу.
  .col-sm-8.col-sm-offset-2
    h4
      | Лист з активацією був відправлений на адресу: 
      strong = current_petitioner.email
      |  o 
      i = current_petitioner.confirmation_sent_at.strftime('%d.%m.%Y %H:%M')
      | .
    br
    br
    br
    p 
      | Не вдається активувати акаунт? Пишіть сюди 
      a href="mailto:alex.hh@me.com" alex.hh@me.com
      | .

app/views/petitioners/sign_in.slim
.row
  .col-xs-5.col-center
    h2
      | Подати документи
    i Ви повинні мати обліковий запис. Якщо у Вас його немає - натисніть "Створити обліковий запис"
    hr
    = form_for(@petitioner, url: petitioner_session_path) do |f|
      .field
        = f.email_field :email, class: 'w100 form-control floating-label', required: true, placeholder: 'Емейл'
      br
      .field
        = f.password_field :password, autocomplete: "off", class: 'w100 form-control floating-label', required: true, placeholder: 'Пароль'
      - if devise_mapping.rememberable?
        .checkbox
          label
            = f.check_box :remember_me
            span style='margin-left:15px;' Запам’ятати мене

        br
      .actions
        = f.submit "Увійти", class: 'btn btn-primary'
        = link_to 'Створити обліковий запис', new_petitioner_registration_path, class: 'btn btn-warning f-right'
      br
      = link_to 'Не вдається згадати пароль?', new_petitioner_password_path

app/views/petitioners/sign_up.slim
.row
  .col-xs-5.col-center
    h2
      | Новий обліковий запис
    i Всі поля обов’язкові
    - if flash.any?
      = render 'shared/flash_notices'
    hr
    = form_for(@petitioner, url: petitioner_registration_path) do |f|
      .field
        = f.email_field :email, class: 'w100 form-control floating-label', required: true, placeholder: 'Емейл'
      br
      .field
        = f.text_field :name, class: 'w100 form-control floating-label', required: true, placeholder: 'Повне ім’я'
      br
      .field
        = f.text_field :phone, class: 'w100 form-control floating-label', required: true, placeholder: 'Номер телефону'
      br
      .field
        = f.text_area :post, class: 'w100 form-control floating-label', required: true, placeholder: 'Посада', rows: 2
      br
      .field
        = f.text_area :workplace, class: 'w100 form-control floating-label', required: true, placeholder: 'Місце роботи', rows: 5
      br
      .field
        = f.text_area :address, class: 'w100 form-control floating-label', required: true, placeholder: 'Поштова адреса', rows: 5
      br
      .field
        = f.password_field :password, autocomplete: "off", class: 'w100 form-control floating-label', required: true, placeholder: 'Пароль'
      br
      .field
        = f.password_field :password_confirmation, autocomplete: "off", class: 'w100 form-control floating-label', required: true, placeholder: 'Повторіть пароль'
        br
      .actions
        = f.submit "Створити запис", class: 'btn btn-primary'
      br
      = link_to 'Увійти', new_petitioner_session_path
      br
      = link_to 'Не вдається згадати пароль?', new_petitioner_password_path