config/routes.rb
Rails.application.routes.draw do

  get 'test', to: 'petitions#test'
  
  root to: 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  devise_for :users

  scope(:path => '/api/v1') do
    resources :profiles
    resources :science_degrees, only: [:index, :show, :update, :create]
    resources :education_degrees, only: [:index, :show, :update, :create]
    resources :workplaces, only: [:index, :show, :update, :create]
    resources :awards, except: [:new, :edit]
    resources :users, except: [:new, :edit]
    resources :award_types, only: [:index, :show, :update, :create]
    resources :award_type_categories, only: [:index]
    resources :petition_initiators, only: [:index, :show, :update, :create]
    resources :document_qualities, only: [:index, :show, :update, :create]
    resources :award_categories, only: [:index]

    get 'petitions/new_count', to: 'admin_petitions#new_count'
    resources :petitions, controller: 'admin_petitions', as: 'admin_petitions' do
      member do
        get 'similar'
        post 'import'
      end
    end

    resources :petitioners
    get 'account/current', to: 'application#current_account'

    resources :reports, only: [:create, :index]
  end

  # petitions
  resources :petitions
  devise_for :petitioners, controllers: {
    sessions: 'petitioners/sessions',
    registrations: 'petitioners/registrations',
    confirmations: 'petitioners/confirmations'
  }
end

app/views/layouts/_admin_menu.slim
li.active
  a href="#" ui-sref="selects"
    | Генерація звітів
li.active
  a href="#" ui-sref="petitions"
    | Вхідні заявки 
    span.badge.label-warning ng-bind="newPetitions" ng-show="newPetitions > 0"
li.active
  a href="#" ui-sref="profileNew"
    | Додати анкету

li.active
  a href=destroy_user_session_path data-method="DELETE"
    | Вийти

app/views/layouts/_navbar.slim
.container.site-header
  .navbar
    .container-fluid
      .navbar-header
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button" 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/" ui-sref="dashboard"
          img src="/images/logo.png" alt=""/
          span Міністерство освіти і науки України
          h5 Департамент роботи з персоналом та керівними кадрами
      .navbar-collapse.collapse.navbar-responsive-collapse
        //form.navbar-form.navbar-left
        //  .form-group
        //    input.form-control.col-md-8 placeholder="Search" type="text" /
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            = render 'layouts/admin_menu'
          - elsif petitioner_signed_in?
            = render 'layouts/petitioner_menu'
          - else 
            li.active
              a href=new_user_session_path
                | Увійти
            li.active
              a href=new_petitioner_session_path
                | Подати документи
  

app/views/layouts/_petitioner_menu.slim
li.active.btn-info
  a href=new_petition_path
    | Додати заявку
li.active
  a href=petitions_path
    | Заявки
li.active
  a href=destroy_petitioner_session_path data-method="DELETE"
    | Вийти

app/views/layouts/angular.slim
doctype html
html ng-app="orden"
  head
    title
      | Департамент роботи з персоналом та керівними кадрами
    link href=("/favicon.ico") rel=("shortcut icon") type="image/x-icon"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body ng-controller="MainCtrl as main"
    = render 'layouts/navbar'
    .maincontent.container.b-white
      .inner.main ui-view=""
    toaster-container
    - if flash.any?
      - flash.each do |name, msg|
        - status = name.to_s == 'notice' ? 'success' : 'danger'
        javascript:
          toastr["#{status}"]("#{msg}")

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Департамент роботи з персоналом та керівними кадрами
    link href=("/favicon.ico") rel=("shortcut icon") type="image/x-icon"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    #maincontent.container
      .inner.main
        - if flash.any?
          br
          .row
            .span12.offset3
              - flash.each do |name, msg|
                - if msg.is_a?(String)
                  div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
                    button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
                    = content_tag :div, msg, :id => "flash_#{name}"
        == yield